### ISSUE TITLE
adding more languages

### ISSUE THREAD

**Issue by SandeepVashishtha** [SandeepVashishtha/Code-Editor#1]
more languages to add

**Comment by LyubomirT** [comment]
I think that adding more languages will require us to re-implement the process of running code, as most languages either require a compiler or an interpreter, and JavaScript can run directly in the browser.

**Comment by SandeepVashishtha** [comment]
@LyubomirT yeah it will

**Comment by kartikey2001** [comment]
Hi @SandeepVashishtha ,
I'd like to take this up.. if you'd assign the issue to me.
I can add python as a language for you. as well as add a dropdown menu, and do some ui fixes.
