### ISSUE TITLE
Even if the function defination delete , it will display the output.

### ISSUE THREAD

**Issue by Adarsh20082006** [SandeepVashishtha/Code-Editor#12]
Even if we delete the `hello_world()` function in Python language, if we call it it will display the output as **Hello, world!**.

**Comment by SandeepVashishtha** [comment]
@Adarsh20082006 if you can fix this then i can assign this to you

**Comment by Amarjeetkumart** [comment]
#### hey, i can solve this problem #12 Assign it to me...
@SandeepVashishtha 


![Screenshot from 2024-10-07 17-34-39](https://github.com/user-attachments/assets/d921196f-2176-4f4f-b3be-31929923a8a8)
