### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by arilloid** [SandeepVashishtha/Code-Editor#16]
I have found your project while searching through repositories participating in Hacktoberfest and noticed that there is a small typo in your README.md.

"Install dependencies::" in the installation section has an extra colon. 

![extra colon](https://github.com/user-attachments/assets/9d145943-d40e-4167-9816-fd53d19fe4aa)

**Comment by SandeepVashishtha** [comment]
Nice 👍, assigned
